name: Unit test

on:
  push:
    branches:
      - main
    paths:
      - '**/**.go'
  pull_request:
    paths:
      - '**/**.go'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository universe && sudo apt-get install -y libfuse2
    
    - name: Run unit tests
      run: make test