name: Build viamrtsp for Android

on:
  push:
  pull_request:
    paths-ignore:
      - 'README.md' 

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository universe &&
        sudo apt-get install -y wget unzip

    - name: Download and extract Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26-linux.zip
        yes A | unzip android-ndk-r26-linux.zip -d ~/
    
    - name: Build viamrtsp for Android
      run: |
        TARGET_OS=android TARGET_ARCH=arm64 make
