name: Build & publish viamrtsp module for Android

on:
  release:
    types: [published]

jobs:
  publish-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
    
    - name: Build viamrtsp binary and package module
      run: |
        TARGET_OS=android TARGET_ARCH=arm64 make module
    
    - name: Upload viamrtsp module to registry
      uses: viamrobotics/upload-module@main
      if: startsWith(github.ref, 'refs/tags/') 
      with:
        meta-path: meta.json
        module-path: module.tar.gz
        platform: android/arm64
        version: ${{ github.ref_name }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
