name: Integration test using mediamtx

on: [push, pull_request]

jobs:
  test-on-ubuntu:
    name: Test on Ubuntu Latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - name: "h264"
            ffmpeg_args: "libx264"
          - name: "h265"
            ffmpeg_args: "libx265"
          - name: "mjpeg"
            ffmpeg_args: "mjpeg -huffman 0"
    env:
      mediamtx_arch: "amd64"
      viam_server_arch: "x86_64"
    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Run tests
        run: make integration-test FFMPEG_ARGS="${{ matrix.config.ffmpeg_args }}" MEDIAMTX_ARCH=${{ env.mediamtx_arch }} VIAM_SERVER_ARCH=${{ env.viam_server_arch }}

  test-on-canon:
    name: Test on Canon ARM64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - name: "h264"
            ffmpeg_args: "libx264"
          - name: "h265"
            ffmpeg_args: "libx265"
          - name: "mjpeg"
            ffmpeg_args: "mjpeg -huffman 0"
    env:
      mediamtx_arch: "arm64v8"
      viam_server_arch: "aarch64"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt install binfmt-support qemu-user-static
      
      - name: Launch container and run tests
        run: |
          docker run --rm -d --name antique-arm64 --network host --platform linux/arm64 -v $(pwd):/host -w /host ghcr.io/viamrobotics/antique2:arm64-cache tail -f /dev/null
          sleep 5  # Wait for the container to fully start and stabilize
          docker exec antique-arm64 bash -l -c "sudo apt-get update && sudo apt-get install -y ffmpeg && make integration-test FFMPEG_ARGS='${{ matrix.config.ffmpeg_args }}' MEDIAMTX_ARCH='${{ env.mediamtx_arch }}' VIAM_SERVER_ARCH='${{ env.viam_server_arch }}'"
