name: Integration test using mediamtx

on: [push, pull_request]

jobs:
  test-on-ubuntu:
    name: Test on Ubuntu Latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - name: "h264"
            codec: "libx264"
          - name: "h265"
            codec: "libx265"
          - name: "mjpeg"
            codec: "mjpeg"
            extra_ffmpeg_args: "-huffman 0"
    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y golang-go libfuse2 ffmpeg
      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          codec: ${{ matrix.config.codec }}
          extra_ffmpeg_args: ${{ matrix.config.extra_ffmpeg_args }}

  test-on-qemu:
    name: Test on QEMU ARM64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - name: "h264"
            codec: "libx264"
          - name: "h265"
            codec: "libx265"
          - name: "mjpeg"
            codec: "mjpeg"
            extra_ffmpeg_args: "-huffman 0"
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU and Docker
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Start Docker container
        run: |
          docker run --privileged --detach --name qemu-container --workdir /github/workspace --volume "${{ github.workspace }}:${{ github.workspace }}" --volume "/var/run/docker.sock:/var/run/docker.sock" arm64v8/ubuntu tail -f /dev/null
      - name: Install dependencies in Docker
        run: |
          docker exec qemu-container apt-get update
          docker exec qemu-container apt-get install -y golang-go libfuse2 ffmpeg
      - name: Run tests in Docker
        run: docker exec qemu-container bash -c "cd ${{ github.workspace }} && ./.github/actions/run-tests/action.yml"
        env:
          CODEC: ${{ matrix.config.codec }}
          EXTRA_FFMPEG_ARGS: ${{ matrix.config.extra_ffmpeg_args }}
      - name: Clean up Docker
        run: docker rm -f qemu-container
