name: Integration test using mediamtx

on: [push, pull_request]

jobs:
  test-on-ubuntu:
    name: Test on Ubuntu Latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - name: "h264"
            ffmpeg_args: "libx264"
          - name: "h265"
            ffmpeg_args: "libx265"
          - name: "mjpeg"
            ffmpeg_args: "mjpeg -huffman 0"
    env:
      mediamtx_arch: "amd64"
      viam_server_arch: "x86_64"
    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y golang-go libfuse2 ffmpeg
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Run tests
        run: make integration-test FFMPEG_ARGS="${{ matrix.config.ffmpeg_args }}" MEDIAMTX_ARCH=${{ env.mediamtx_arch }} VIAM_SERVER_ARCH=${{ env.viam_server_arch }}

  test-on-qemu:
    name: Test on QEMU ARM64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - name: "h264"
            codec: "libx264"
          - name: "h265"
            codec: "libx265"
          - name: "mjpeg"
            codec: "mjpeg"
            extra_ffmpeg_args: "-huffman 0"
    env:
      mediamtx_arch: "arm64v8"
      viam_server_arch: "aarch64"
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU and Docker
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Start Docker container
        run: |
          docker run --privileged --detach --name qemu-container --workdir /github/workspace --volume "${{ github.workspace }}:${{ github.workspace }}" --volume "/var/run/docker.sock:/var/run/docker.sock" --net=host arm64v8/ubuntu tail -f /dev/null
      - name: Install dependencies in Docker
        run: |
          docker exec qemu-container apt-get update
          docker exec qemu-container apt-get install -y make golang-go libfuse2 ffmpeg
      - name: Run tests in Docker
        run: docker exec qemu-container bash -c "cd ${{ github.workspace }} && make integration-test FFMPEG_ARGS="${{ matrix.config.ffmpeg_args }}" MEDIAMTX_ARCH=${{ env.mediamtx_arch }} VIAM_SERVER_ARCH=${{ env.viam_server_arch }}"
        env:
          CODEC: ${{ matrix.config.codec }}
          EXTRA_FFMPEG_ARGS: ${{ matrix.config.extra_ffmpeg_args }}
      - name: Clean up Docker
        run: docker rm -f qemu-container
