name: Build & publish module to registry

on:
  release:
    types: [published]

jobs:
  publish:
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, android/arm64]
      
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'buildjet-8vcpu-ubuntu-2204-arm' || 'ubuntu-latest' }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.13

    - name: Build and package
      run: |
        if [[ "${{ matrix.platform }}" == "linux/amd64" ]]; then
          TARGET_OS=linux TARGET_ARCH=amd64 make module
        elif [[ "${{ matrix.platform }}" == "linux/arm64" ]]; then
          TARGET_OS=linux TARGET_ARCH=arm64 make module
        elif [[ "${{ matrix.platform }}" == "android/arm64" ]]; then
          TARGET_OS=android TARGET_ARCH=arm64 make module
        fi

    - name: Upload viamrtsp module to registry
      uses: viamrobotics/upload-module@main
      with:
        meta-path: meta.json
        module-path: module.tar.gz
        platform: ${{ matrix.platform }}
        version: ${{ github.ref_name }}
        key-id: ${{ secrets.VIAM_DEV_API_KEY_ID }}
        key-value: ${{ secrets.VIAM_DEV_API_KEY }}
