name: Build & publish module to registry

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  publish:
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, android/arm64]
      
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'buildjet-8vcpu-ubuntu-2204-arm' || 'ubuntu-latest' }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Install canon
      run: |
        export PATH="$(go env GOPATH)/bin:$PATH"
        go install github.com/viamrobotics/canon@latest
    
    - name: Launch canon
      run: |
        if [[ "${{ matrix.platform }}" == "linux/amd64" ]]; then
          canon -profile viam-rtsp-antique -arch amd64
        else
          canon -profile viam-rtsp-antique -arch arm64
        fi

    - name: Build and package
      run: |
        if [[ "${{ matrix.platform }}" == "linux/amd64" ]]; then
          canon TARGET_OS=linux TARGET_ARCH=amd64 make module
        elif [[ "${{ matrix.platform }}" == "linux/arm64" ]]; then
          canon TARGET_OS=linux TARGET_ARCH=arm64 make module
        elif [[ "${{ matrix.platform }}" == "android/arm64" ]]; then
          canon TARGET_OS=android TARGET_ARCH=arm64 make module
        fi

    - name: Upload viamrtsp module to registry
      uses: viamrobotics/upload-module@main
      with:
        meta-path: meta.json
        module-path: module.tar.gz
        platform: ${{ matrix.platform }}
        version: ${{ github.ref_name }}
        key-id: ${{ secrets.VIAM_DEV_API_KEY_ID }}
        key-value: ${{ secrets.VIAM_DEV_API_KEY }}
