name: Build & publish module to registry 

on:
  release:
    types: [published]

jobs:
  publish:
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, android/arm64]
        runner: [ubuntu-latest, buildjet-8vcpu-ubuntu-2204-arm]
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: buildjet-8vcpu-ubuntu-2204-arm
          - platform: android/arm64
            runner: ubuntu-latest

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.13

    - name: Build viamrtsp binary and package module
      run: |
        if [[ "${{ matrix.platform }}" == "linux/amd64" ]]; then
          TARGET_OS=linux TARGET_ARCH=amd64 make module
        elif [[ "${{ matrix.platform }}" == "linux/arm64" ]]; then
          TARGET_OS=linux TARGET_ARCH=arm64 make module
        elif [[ "${{ matrix.platform }}" == "android/arm64" ]]; then
          TARGET_OS=android TARGET_ARCH=arm64 make module
        fi

    - name: Upload viamrtsp module to registry
      uses: viamrobotics/upload-module@main
      with:
        meta-path: meta.json
        module-path: module.tar.gz
        platform: ${{ matrix.platform }}
        version: ${{ github.ref_name }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
