name: Build & publish module to registry 

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - run_command: "TARGET_OS=android TARGET_ARCH=arm64 make module"
            canon_arch: "amd64"
            platform: android/arm64
          - run_command: "make module"
            canon_arch: "arm64"
            platform: linux/arm64
          - run_command: "make module"
            canon_arch: "amd64"
            platform: linux/amd64
    container:
      image: ghcr.io/viamrobotics/antique2:${{ matrix.canon_arch }}-cache

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    # - name: Install QEMU
    #   run: |
    #     sudo apt-get update
    #     sudo apt install binfmt-support qemu-user-static

    # - name: Install canon
    #   run: |
    #     go install github.com/viamrobotics/canon@latest
    
    # - name: Launch canon
    #   run: |
    #     canon -profile viam-rtsp-antique -arch ${{ matrix.canon_arch }}

    - name: Build module
      run: ${{ matrix.run_command }}

    - name: Upload viamrtsp module to registry
      uses: viamrobotics/upload-module@main
      if: startsWith(github.ref, 'refs/tags/') 
      with:
        meta-path: meta.json
        module-path: module.tar.gz
        platform: ${{ matrix.platform }}
        version: ${{ github.ref_name }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
